### ISSUE TITLE
ModuleNotFoundError: No module named 'koder_utils'

### ISSUE THREAD

**Issue by sergeygalkin** [sergeygalkin/disk_perf_test_tool#2]
Steps to reproduce
1. Build docker image
2. Run with `docker run -ti  --rm --name wally image/name`
3. Run wally
```
root@a7a12b03be42:/# wally 
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/wally/wally/__main__.py", line 2, in <module>
    from .main import main
  File "/opt/wally/wally/main.py", line 23, in <module>
    from cephlib.texttable import Texttable
  File "/opt/cephlib/cephlib/__init__.py", line 1, in <module>
    from .raw_classes import (CephHealth, CephRole, OSDStatus, CephStatusCode, MonRole, CephRelease, OSDStoreType, PGState,
  File "/opt/cephlib/cephlib/raw_classes.py", line 11, in <module>
    from koder_utils import DiskType, ConvBase, field, IntArithmeticMixin, register_converter, ToInt, ToFloat
ModuleNotFoundError: No module named 'koder_utils'
```

**Comment by sergeygalkin** [comment]
Fixed by https://github.com/sergeygalkin/disk_perf_test_tool/commit/ad150b8e01f52339f832ad0c29a9352239f013a9
