### ISSUE TITLE
ModuleNotFoundError: No module named 'cephlib.texttable'

### ISSUE THREAD

**Issue by sergeygalkin** [sergeygalkin/disk_perf_test_tool#3]
Steps to reproduce
1. Build docker image from commit https://github.com/sergeygalkin/disk_perf_test_tool/commit/ad150b8e01f52339f832ad0c29a9352239f013a9
2. Run with docker run -ti --rm --name wally image/name
3. Run wally
```
root@ffd46c6e736b:/# wally
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/wally/wally/__main__.py", line 2, in <module>
    from .main import main
  File "/opt/wally/wally/main.py", line 23, in <module>
    from cephlib.texttable import Texttable
ModuleNotFoundError: No module named 'cephlib.texttable'
```

**Comment by morissette** [comment]
I get:
```
File "/opt/cephlib/cephlib/raw_classes.py", line 11, in <module>
    from koder_utils import DiskType, ConvBase, field, IntArithmeticMixin, register_converter, ToInt, ToFloat
ModuleNotFoundError: No module named 'koder_utils'
root@18fc1b4fbbfe:/# pip install koder_utils
ERROR: Could not find a version that satisfies the requirement koder_utils (from versions: none)
ERROR: No matching distribution found for koder_utils
```
